[package]
name = "ground-openapi"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Jezza/ground"

[dependencies]
axum = "0.7.7"
headers-core = "0.3.0"
http = "1.1.0"
http-body = "1.0.1"

mime = "0.3.17"

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

tracing = "0.1.40"

serde_html_form = "0.2.6"

async-trait = "0.1.83"
thiserror = "1.0.64"
bytes = "1.7.2"

[lints]
workspace = true
