use ground_codegen_utils::case;
use ground_openapi_utils as utils;
use ground_openapi_utils::visitor::type_visit_mut::TypeVisitMut;
use ground_openapi_utils::visitor::visit_mut;
use ground_openapi_utils::visitor::visit_mut::VisitMut;
use openapiv3::{OpenAPI, Operation, Paths, ReferenceOr, Schema};
use serde_json::Value;

use crate::{GROUND_EXTERNAL, GROUND_EXTERNAL_TYPES, GROUND_NAME, GROUND_TAGS};

pub fn build(opts: BuilderOpts, paths: Vec<Paths>) -> anyhow::Result<OpenAPI> {
    let mut builder = ApiBuilder::new(opts);

    for mut paths in paths {
        // Copy the tags over
        if let Some(tags) = paths.extensions.swap_remove(GROUND_TAGS) {
            let tags: Vec<openapiv3::Tag> = serde_json::from_value(tags).expect("Tags are invalid");
            builder.openapi.tags.extend(tags);
        }

        if let Some(types) = paths.extensions.swap_remove(GROUND_EXTERNAL_TYPES) {
            let types: indexmap::IndexMap<String, Schema> =
                serde_json::from_value(types).expect("External types are invalid");

            for (_, ty) in types {
                let Some(Value::String(name)) = ty.schema_data.extensions.get(GROUND_NAME) else {
                    panic!("Unnamed external.");
                };
                let name = name.clone();
                let Some(Value::Bool(true)) = ty.schema_data.extensions.get(GROUND_EXTERNAL) else {
                    panic!("External wasn't marked as such: {}", name);
                };

                builder.visit_reference_or_schema_mut(&mut ReferenceOr::Item(ty));
            }
        }

        builder.visit_paths_mut(&mut paths);
        builder.openapi.paths.paths.extend(paths.paths);
    }

    builder
        .openapi
        .tags
        .sort_by(|left, right| left.name.cmp(&right.name));
    builder
        .openapi
        .tags
        .dedup_by(|left, right| left.name == right.name);

    if let Some(components) = builder.openapi.components.as_mut() {
        components.schemas.sort_keys();
    }

    Ok(builder.openapi)
}

#[derive(Debug, Clone)]
pub struct BuilderOpts {
    // This marks externals used within the input explicitly as "external".
    // This lets you easily distinguish internal vs external types visually.
    // (ie, you'd see `ground_api::external::ApiError` vs `crate::models::ApiError`)
    // `external` _doesn't_ mean things like "Uuid" (those are "known" types)
    //
    // Implementation-wise, disabling this strips the "external:" part of the reference that we use to identify externals.
    // We use the external prefix to specifically mark the path in the generated code.
    // pub explicit_externals: bool,
}

impl Default for BuilderOpts {
    fn default() -> Self {
        Self {
            // explicit_externals: false,
        }
    }
}

struct ApiBuilder {
    // opts: BuilderOpts,
    pub openapi: OpenAPI,
}

impl ApiBuilder {
    pub fn new(_opts: BuilderOpts) -> Self {
        // @TODO jezza - 07 Oct 2024: Support custom security mechanisms.

        Self {
            openapi: OpenAPI {
                openapi: "3.0.3".to_string(),
                info: openapiv3::Info {
                    title: "Api (generated by ground)".to_string(),
                    version: "v0.0.1".to_string(),
                    ..Default::default()
                },
                components: Some(openapiv3::Components::default()),
                ..Default::default()
            },
            // opts,
        }
    }
}

impl<'a> TypeVisitMut<'a> for ApiBuilder {
    type Outcome = ();

    fn visit_reference_or_schema_mut(&mut self, node: &'a mut ReferenceOr<Schema>) {
        let ReferenceOr::Item(item) = node else {
            return;
        };

        let name = utils::ext_str(&item.schema_data.extensions, GROUND_NAME).map(String::from);

        let external = if utils::check_ext(&item.schema_data.extensions, GROUND_EXTERNAL) {
            "external:"
        } else {
            ""
        };

        self.visit_schema_mut(item);

        let Some(name) = name else {
            return;
        };

        let mut reference = ReferenceOr::Reference {
            reference: format!("{}#/components/schemas/{}", external, name),
        };

        std::mem::swap(node, &mut reference);

        let components = self.openapi.components.as_mut().expect("Should be set");

        if components.schemas.contains_key(&name) {
            // let stored = components
            //     .schemas
            //     .get(&name)
            //     .expect("We just checked it.")
            //     .as_item()
            //     .expect("We don't store references");

            // let reference = reference.into_item().expect("Should be an item");

            // @TODO jezza - 07 Oct 2024: Add some type signature crap. (Validating that the thing that we're actually using is the same.)
            // let have =
            //     serde_json::to_string_pretty(&reference).expect("Unable to repr schema as json");
            // let stored =
            //     serde_json::to_string_pretty(stored).expect("Unable to repr schema as json");

            // assert_eq!(have, stored);

            return;
        }

        components.schemas.insert(name, reference);
    }

    fn visit_reference_or_box_schema_mut(&mut self, node: &'a mut ReferenceOr<Box<Schema>>) {
        let ReferenceOr::Item(item) = node else {
            return;
        };

        let name = utils::ext_str(&item.schema_data.extensions, GROUND_NAME).map(String::from);

        let external = if utils::check_ext(&item.schema_data.extensions, GROUND_EXTERNAL) {
            "external:"
        } else {
            ""
        };

        self.visit_schema_mut(item);

        let Some(name) = name else {
            return;
        };

        let mut reference = ReferenceOr::Reference {
            reference: format!("{}#/components/schemas/{}", external, name),
        };

        std::mem::swap(node, &mut reference);

        let components = self.openapi.components.as_mut().expect("Should be set");

        if components.schemas.contains_key(&name) {
            // let stored = components
            //     .schemas
            //     .get(&name)
            //     .expect("We just checked it.")
            //     .as_item()
            //     .expect("We don't store references");

            // let reference = reference.into_item().expect("Should be an item");

            // @TODO jezza - 07 Oct 2024: Add some type signature crap. (Validating that the thing that we're actually using is the same.)
            // let have =
            //     serde_json::to_string_pretty(&reference).expect("Unable to repr schema as json");
            // let stored =
            //     serde_json::to_string_pretty(stored).expect("Unable to repr schema as json");

            // assert_eq!(have, stored);

            return;
        }

        components.schemas.insert(name, reference.unbox());
    }
}

impl<'a> VisitMut<'a> for ApiBuilder {
    fn visit_paths_mut(&mut self, node: &'a mut Paths) {
        visit_mut::visit_paths_mut(self, node);

        let mut map = indexmap::IndexMap::new();
        std::mem::swap(&mut map, &mut node.paths);

        // Each path item contains the name of the originating api it came from.
        // We do this, so we can differentiate differing routes and operation ids.
        // API routes that come from the same api will collide.
        // Eg, ops and partner apis will both have operations that use the same operation id.
        let Some(Value::String(name)) = node.extensions.get(GROUND_NAME) else {
            panic!("Paths have no tags")
        };
        let name = name.clone();

        for (path, mut item) in map.into_iter() {
            // if !self.opts.include_hidden_routes && path.starts_with("/inc/") {
            //     continue;
            // }

            let path = format!("/{}__{}", name, path);

            if let ReferenceOr::Item(item) = &mut item {
                utils::visit_op_mut(item, |_, op| {
                    if let Some(id) = op.operation_id.as_mut() {
                        id.insert_str(0, &format!("{}__", name));
                    }
                });
            }

            if let Some(previous) = node.paths.insert(path.clone(), item) {
                panic!("URL collision: {}: {:#?}", path, previous);
            }
        }
    }

    fn visit_operation_mut(&mut self, node: &'a mut Operation) {
        // Recursively replace all the schemas, etc, before we start working on it.
        visit_mut::visit_operation_mut(self, node);

        let Some(req_body) = node.request_body.as_mut() else {
            return;
        };

        let operation_id = node
            .operation_id
            .as_deref()
            .expect("Operations should have operation ids");
        let operation_id = case::convert(operation_id, case::Case::Pascal);

        let tag = node
            .tags
            .first()
            .map(|item| format!("{}.", item))
            .unwrap_or_default();

        let full_name = format!("{}{}Request", tag, operation_id);
        let full_reference = format!("#/components/requestBodies/{}", full_name);

        let mut reference = ReferenceOr::Reference {
            reference: full_reference,
        };
        std::mem::swap(req_body, &mut reference);

        let components = self.openapi.components.as_mut().expect("Should be set");
        components.request_bodies.insert(full_name, reference);
    }
}
